version: '3.8'

services:
  db:
    container_name: postgres-container
    image: postgres:15
    environment:
      POSTGRES_USER: ${LOCAL_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${LOCAL_DB_PASSWORD:-postgres}
      POSTGRES_DB: ${LOCAL_DB_NAME:-salaries_db}
    ports:
      - "${LOCAL_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
